repo: Do not create the mirror symlink
repo since 1.13.12 checks for path out of scope for copyfile/lnkfile
nodes in the manifest:
https://gerrit.googlesource.com/git-repo/+/04122b7261319dae3abcaf0eb63af7ed937dc463

The manifest currently fail with:
error.ManifestInvalidPathError: <linkfile> invalid "src": ../../.repo/projects/openxt/: bad component: ..

Change-Id: Ie783e02bbb6245258e7eb8b589cdace6ee8f5467
Signed-off-by: Eric Chanudet <chanudete@ainfosec.com>